name: Build libmpv-android

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: write

env:
  NDK_VER: 25.1.8937393

jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive        # 关键：拉取子模块

      - name: Setup Java JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 11

      - name: Setup Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Cache NDK
        uses: actions/cache@v4
        with:
          path: /usr/local/lib/android/sdk/ndk/${{ env.NDK_VER }}
          key: ${{ runner.os }}-ndk-${{ env.NDK_VER }}

      - name: Install system deps
        run: |
          sudo apt-get update
          sudo apt-get install -y autoconf automake cmake libtool ninja-build pkg-config unzip curl git

      - name: Create SDK symlink
        working-directory: ./buildscripts
        run: |
          mkdir -p sdk
          ln -sf "$ANDROID_HOME" sdk/android-sdk-linux

      - name: Grant execute permission to all scripts
        run: |
          find buildscripts -type f -name "*.sh" -exec chmod +x {} +

      - name: Run bundle_default.sh
        working-directory: ./buildscripts
        run: ./bundle_default.sh

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: artifact
          path: ./output/*

      - name: Create GitHub release (main only)
        if: github.ref == 'refs/heads/main'
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          prerelease: false
          tag_name: vnext
          files: output/*
